;; Wins directed graph for the NFL 2008 regular season
((Chargers Jets Patriots Raiders Chiefs Buccaneers Broncos)
 (Broncos Raiders Chargers Saints Buccaneers Browns Falcons Jets Chiefs)
 (Cardinals Dolphins Bills Cowboys 49ers Rams Seahawks)
 (Seahawks 49ers Rams Jets)
 (Eagles Rams Steelers 49ers Falcons Seahawks Cardinals Giants Browns Cowboys)
 (Cowboys Browns Eagles Packers Bengals Buccaneers Redskins 49ers Seahawks Giants)
 (Dolphins Patriots Chargers Broncos Seahawks Raiders Rams Bills 49ers Chiefs Jets)
 (Jets Dolphins Cardinals Bengals Chiefs Rams Patriots Titans Bills)
 (Ravens Dolphins Raiders Browns Texans Eagles Bengals Redskins Cowboys Jaguars)
 (Jaguars Colts Texans Broncos Lions Packers)
 (49ers Seahawks Lions Bills Jets Rams Redskins)
 (Redskins Saints Cardinals Cowboys Browns Lions Seahawks Eagles)
 (Texans Dolphins Lions Bengals Browns Jaguars Packers Titans Bears)
 (Bears Colts Eagles Vikings Lions Rams Jaguars Saints Packers)
 (Raiders Chiefs Jets Broncos Texans Buccaneers)
 (Buccaneers Falcons Bears Packers Panthers Seahawks Chiefs Lions Saints)
 (Steelers Texans Jaguars Redskins Chargers Bengals Patriots Cowboys Ravens Browns)
 (Browns Bengals Giants Jaguars)
 (Panthers Chargers Bears Falcons Chiefs Cardinals Raiders Lions Packers Buccaneers Broncos Saints)
 (Saints Buccaneers 49ers Raiders Chargers Chiefs Packers Falcons Lions)
 (Vikings Panthers Saints Texans Packers Jaguars Bears Lions Cardinals Giants)
 (Giants Rams Bengals Seahawks 49ers Steelers Cowboys Eagles Ravens Cardinals Redskins Panthers)
 (Colts Vikings Ravens Patriots Steelers Texans Chargers Browns Bengals Lions Jaguars Titans)
 (Titans Bengals Texans Vikings Ravens Chiefs Colts Packers Bears Jaguars Lions Browns Steelers)
 (Packers Vikings Seahawks Colts Bears Lions)
 (Lions)
 (Bengals Jaguars Eagles Redskins Browns Chiefs)
 (Chiefs Broncos Raiders)
 (Patriots Chiefs Jets 49ers Broncos Rams Dolphins Seahawks Raiders Cardinals Bills)
 (Bills Seahawks Jaguars Raiders Rams Chargers Chiefs Broncos)
 (Falcons Lions Chiefs Packers Bears Raiders Saints Panthers Chargers Buccaneers Vikings Rams)
 (Rams Redskins Cowboys))
