;; Wins directed graph for the NFL 2009 regular season
((Bengals Packers Bears Ravens Steelers Browns Lions Chiefs)
 (Jets Texans Patriots Titans Raiders Panthers Bills Buccaneers Colts Bengals)
 (Titans Jaguars 49ers Bills Texans Cardinals Rams Dolphins Seahawks)
 (Seahawks Jaguars Lions Rams 49ers)
 (Redskins Rams Buccaneers Broncos Raiders)
 (Chargers Dolphins Raiders Giants Eagles Broncos Chiefs Browns Cowboys Bengals Titans Redskins)
 (Packers Rams Browns Cowboys 49ers Lions Ravens Bears Seahawks Cardinals)
 (Cardinals Jaguars Texans Giants Bears Seahawks Vikings Lions Rams)
 (Ravens Chiefs Chargers Broncos Browns Steelers Lions Bears Raiders)
 (Raiders Chiefs Eagles Bengals Steelers Broncos)
 (Chiefs Redskins Raiders Steelers Broncos)
 (Broncos Bengals Browns Raiders Cowboys Patriots Chargers Giants Chiefs)
 (Eagles Panthers Chiefs Buccaneers Redskins Falcons Giants 49ers Broncos)
 (Cowboys Buccaneers Chiefs Falcons Seahawks Raiders Saints Redskins Eagles)
 (Patriots Falcons Ravens Titans Buccaneers Dolphins Jets Panthers Bills Jaguars)
 (Texans Titans Raiders Bengals 49ers Bills Seahawks Rams Dolphins Patriots)
 (Saints Lions Eagles Bills Jets Giants Dolphins Panthers Rams Buccaneers Patriots Redskins Falcons)
 (Panthers Redskins Cardinals Falcons Buccaneers Vikings Giants Saints)
 (Falcons Dolphins Panthers 49ers Bears Redskins Jets Bills Buccaneers)
 (Buccaneers Packers Seahawks Saints)
 (Giants Buccaneers Chiefs Raiders Falcons Cowboys Redskins)
 (Vikings Browns 49ers Rams Ravens Packers Lions Seahawks Bears Bengals Giants)
 (Steelers Titans Chargers Lions Browns Vikings Broncos Packers Ravens Dolphins)
 (Dolphins Bills Jets Buccaneers Panthers Patriots Jaguars)
 (49ers Seahawks Bears Jaguars Cardinals Lions Rams)
 (Rams Lions)
 (Bears Steelers Seahawks Browns Eagles Rams Vikings Lions)
 (Lions Redskins Browns)
 (Colts Dolphins Cardinals Seahawks Rams 49ers Patriots Ravens Texans Titans Broncos Jaguars)
 (Bills Buccaneers Jets Panthers Dolphins Chiefs Colts)
 (Jaguars Titans Rams Chiefs Jets Bills Texans)
 (Browns Bills Steelers Chiefs Raiders Jaguars))
